"""empty message

Revision ID: 4145456edb
Revises: None
Create Date: 2015-12-30 18:20:01.134462

"""

# revision identifiers, used by Alembic.
revision = '4145456edb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'entry',
        sa.Column('status', sa.SmallInteger(), server_default='0')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'status')
    ### end Alembic commands ###
