"""empty message

Revision ID: 59584c946a4
Revises: 48f988c8fd0
Create Date: 2016-01-03 07:19:10.422014

"""

# revision identifiers, used by Alembic.
revision = '59584c946a4'
down_revision = '48f988c8fd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entry', 'user', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.drop_column('entry', 'author_id')
    ### end Alembic commands ###
